#=====Intead of this
#malak.pro1.value = 1
#malak.pro2.value = 2

# ====> Try this
# malak:
#     pro1:
#         value: 2

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mytest
        username: postgres
        password: malak1
        driver-class-name : org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true