name : Build & Deploy Spring app


on:
  push:
    branches:
      - master # could be list of branches : dev branch


jobs:
  build-deploy:
    name: Build and Deploy Spring boot Refresh Demo
    runs-on: ubuntu-latest  # runners : machine in which we want to run this actions( default or create your own machine )
    # to perform all steps
    steps: # each job has different steps

      # github Actions will go and copy the code from github repo  and cone it into the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Need to set up + install JDK 17 !! springboot 3.2 is using it
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      # Test installation : not using action but manual test : mvn test , clean instal etc
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |  # use this pipe because we have multiple commands
          mvn clean  
          mvn -B package --file pom.xml

      # Add docker bulid step
      - name: Build Docker Image
        uses: docker/build-push-action@v5 # build docker image out of docker file we need to specify
        with:  # with used to specify parameters needed
          context: . # . = use current file of docker in the based source app
          dockerfile: Dockerfile
          push: false  # to check if we are able to build the image or not
          # user credential of docker hub ==> create secrets
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/refreshing-SpringBoot:latest # today  ?? $(date-'%Y%m%d%H%M%S') ?

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/refreshing-SpringBoot:latest # today ?? : $(date-'%Y%m%d%H%M%S') ?
