name : Build & Deploy Spring app

on:
  push:
    branches:
      - main # could be list of branches : dev branch

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest  # runners : machine in which we want to run this actions( default or create your own machine )
                            # to perform all steps
    steps: # each job has different steps

      # github Actions will go and copy the code from github repo  and cone it into the runner
      - name: Checkout code
        uses: actions/checkout@v4

      # Need to set up + install JDK 17 !! springboot 3.2 is using it
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

      # Test installation : not using action but manual test : mvn test , clean instal etc
      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |  # use this pipe because we have multiple commands
          mvn clean   
          mvn -B package --file pom.xml
